<a href="https://colab.research.google.com/github/Joseph-Maulin/DS-Unit-1-Sprint-2-Statistics/blob/master/bayes2_starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Example of a classifier

In [0]:
# EDA and data handling
import numpy as np
import pandas as pd

# Modeling
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [4]:
# read in the data
housing = pd.read_csv('/content/sample_data/california_housing_train.csv')

housing = housing.sample(500)
housing.head()

longitude  latitude  ...  median_income  median_house_value
1460     -117.19     32.81  ...         5.1491            207000.0
13013    -121.86     37.70  ...         6.6827            313700.0
4911     -118.10     33.90  ...         3.6000            156400.0
7710     -118.38     34.10  ...         9.3092            500001.0
6190     -118.24     34.06  ...         1.1979            350000.0

[5 rows x 9 columns]

In [0]:
# reduce the size of the dataset


In [0]:
# show the data 


In [7]:
# Describe the target 
housing['median_house_value'].describe

<bound method NDFrame.describe of 1460     207000.0
13013    313700.0
4911     156400.0
7710     500001.0
6190     350000.0
           ...   
7013     242300.0
10442    115600.0
276      193800.0
1865     100400.0
8330     145400.0
Name: median_house_value, Length: 500, dtype: float64>

In [8]:
# create the target 
housing['high_price'] = np.where(housing['median_house_value']>=185900, 1, 0)
housing['high_price'].value_counts()

1    254
0    246
Name: high_price, dtype: int64

In [9]:
# establish the predictors and the target
X = housing.drop(['high_price', 'median_house_value'], axis=1)
X

longitude  latitude  ...  households  median_income
1460     -117.19     32.81  ...       839.0         5.1491
13013    -121.86     37.70  ...      1391.0         6.6827
4911     -118.10     33.90  ...       183.0         3.6000
7710     -118.38     34.10  ...       525.0         9.3092
6190     -118.24     34.06  ...       193.0         1.1979
...          ...       ...  ...         ...            ...
7013     -118.31     33.88  ...       587.0         3.5644
10442    -120.32     38.71  ...        32.0         3.5667
276      -116.67     32.97  ...        43.0         5.3590
1865     -117.28     34.51  ...       812.0         3.0181
8330     -118.46     34.23  ...      2660.0         2.5850

[500 rows x 8 columns]

In [0]:
y = housing['high_price']

In [0]:
# train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [12]:
len(y_test)

150

In [0]:
# instantiate the classifier
mymodel = RandomForestClassifier()

In [14]:
# fit on the training data
mymodel.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
# predict on the testing data
y_preds = mymodel.predict(X_test)

In [17]:
# check out the first few neighborhoods
print(y_test.values[:10], 'true values')
print(y_preds[:10], 'predicted values')


[1 1 0 0 0 1 0 1 1 1] true values
[0 0 1 0 0 1 0 1 1 1] predicted values


In [19]:
# evaluate the model performance
metrics.accuracy_score(y_test, y_preds)

0.7466666666666667

## Confusion Matrix

In [0]:
# examine the confusion matrix
m = metrics.confusion_matrix(y_test, y_preds)

In [24]:
cm = pd.DataFrame(m, columns=['pred_0', 'pred_1'])
cm

pred_0  pred_1
0      57      14
1      24      55

* 55 true positives (TP): These are cases in which we predicted yes (pricey house), and it is indeed a pricey house.
* 57 true negatives (TN): We predicted no (cheap house), and the house is indeed cheap.
* 14 false positives (FP): We predicted yes (pricey house), but the house isn't pricey. (Also known as a "Type I error.")
* 24 false negatives (FN): We predicted no (cheap house), but the house is actually pricey. (Also known as a "Type II error.")

In [0]:
# get the numbers
TN = cm['pred_0'].values[0]
FN = cm['pred_0'].values[1]
FP = cm['pred_1'].values[0]
TP = cm['pred_1'].values[1]
ALL = cm.values.sum()

In [36]:
print('True Negatives:', TN)
print('False Negatives:', FN)
print('False Positives:', FP)
print('True Positives:', TP)
print('All:', ALL)

True Negatives: 57
False Negatives: 24
False Positives: 14
True Positives: 55
All: 150


**Accuracy:**  
Overall, how often is it correct?

In [37]:
print(f'Accuracy: {round((TP+TN)/ALL, 2)}')

Accuracy: 0.75


**True Positive Rate:**   
When it's actually yes, how often does it predict yes?        
“Sensitivity” or “Recall”

In [39]:
print(f'True Positive Rate: {round(TP/(TP+FN),4)}')

True Positive Rate: 0.6962


**False Positive Rate:**    
When it's actually no, how often does it predict yes?   
Also known as "Fall-out Rate"

In [42]:
print(f'False Positive Rate:  {round(FP/(FP+TN),4)}')

False Positive Rate:  0.1972


**Precision:**     
When it predicts yes, how often is it correct?  
Also known as "Positive Predictive Value (PPV)"

In [43]:
print(f'Precision: {round(TP / (TP+FP), 4)}')

Precision: 0.7971


**Specificity:**  
When it's actually no, how often does it predict no?    
also known as "True Negative Rate"

In [44]:
print(f'Specificity: {round(TN / (TN + FP), 2)}')

Specificity: 0.8


**Prevalence:**    
How often does the yes condition actually occur in our sample?  
actual yes/total

In [45]:
print(f'Prevalence: {round((TP+FN)/ALL, 4)}')

Prevalence: 0.5267


## Again

In [46]:
# House age
housing['housing_median_age'].describe()

count    500.000000
mean      28.996000
std       12.760472
min        2.000000
25%       18.000000
50%       29.000000
75%       38.000000
max       52.000000
Name: housing_median_age, dtype: float64

In [0]:
# Create a target
housing['old'] = np.where(housing['housing_median_age']>=38, 1, 0)

In [0]:
# establish the predictors and the target
X = housing.drop(['old', 'housing_median_age', 'high_price'], axis=1)
y = housing['old']

In [0]:
# train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [0]:
# instantiate the classifier
mymodel = RandomForestClassifier()

In [52]:
# fit on the training data
mymodel.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
# predict on the testing data
y_preds = mymodel.predict(X_test)

In [55]:
# check out the first few houses
print(y_test.values[0:10], 'ground truth')
print(y_preds[:10], 'predictions')

[0 1 0 0 1 0 0 0 1 1] ground truth
[0 0 0 0 0 0 0 0 0 1] predictions


In [56]:
# evaluate the model performance
metrics.accuracy_score(y_test, y_preds)

0.7533333333333333

In [57]:
# examine the confusion matrix
cm = pd.DataFrame(metrics.confusion_matrix(y_test, y_preds), columns=['pred_0', 'pred_1'])
cm

pred_0  pred_1
0     104       4
1      33       9

In [0]:
# get the numbers
# get the numbers
TN = cm['pred_0'].values[0]
FN = cm['pred_0'].values[1]
FP = cm['pred_1'].values[0]
TP = cm['pred_1'].values[1]
ALL = cm.values.sum()

In [59]:
print(f'Accuracy: {round((TP+TN)/ALL, 4)}')
print(f'True Positive Rate: {round(TP/(TP+FN), 4)}')
print(f'False Positive Rate: {round(FP/(FP+TN), 4)}')
print(f'Precision: {round(TP/(TP+FP), 4)}')
print(f'Specificity: {round(TN/(TN+FP), 4)}')
print(f'Prevalence: {round((TP+FN)/ALL, 4)}')

Accuracy: 0.7533
True Positive Rate: 0.2143
False Positive Rate: 0.037
Precision: 0.6923
Specificity: 0.963
Prevalence: 0.28


## Terminology

| Bayes term | Bayes formula | Confusion Matrix term | Confusion Matrix formula| Alternative CM term | 
|:-|:-|:-|:-|:-|
| prior | P(A) | prevalence | (TP + FN) / (TP+TN+FP+FN) | ? |
| posterior | P(A given B) | Positive Predictive Value (PPV) | TP / (TP + FP) | precision |
| conditional | P(B given A) | True Positive Rate (TPR)  |TP / (TP + FN) | sensitivity, recall |
| marginal | P(B) | queue rate | TP + FP | ? |  
| prior complement | P(not A) or 100-P(A) | prevalence complement | 1-prevalence | ? |
| ? | P(not B given not A) | True Negative Rate (TNR) | TN / (FP + TN) | specificity |
| ? | P(B given not A) | False Positive Rate (FPR) | FP / (FP+TN) | fall-out rate, false alarm rate |
| ? | P(not B given A) | False Negative Rate (FNR) | FN / (TP + FN) | miss rate |
|?|?|accuracy|(TP + TN) / (TP+TN+FP+FN)|?|
|?|?|error rate|(FP + FN) / (TP+TN+FP+FN)|misclassification rate|


**Abbreviations**  
A: Hypothesized Data       
B: Observed Data         
TP: True Positive  
TN: True Negative  
FP: False Positive  
FN: False Negative  
 
^ Note: Sometimes in Bayesian statistics the following terms are used instead:
 
* prior = hypothesis
* posterior = updated hypothesis
* conditional = likelihood
* marginal = model evidence

## Problem 1. Drunk Drivers

imagine that individuals are taking a breathalyzer test with 
* an 8% false positive rate, 
* a 100% true positive rate, 
* our prior belief about drunk driving in the population is 1/1000. 
* What is the probability that a person is drunk after one positive breathalyzer test?

In [0]:
# write a function
def prob_drunk_givin_positive(prob_drunk_prior, false_positive_rate, true_positive_rate):
  prob_sober = 1-prob_drunk_prior

  numerator = true_positive_rate * prob_drunk_prior
  denomenator = numerator + false_positive_rate * prob_sober

  posterior = numerator/denomenator
  
  return posterior

In [63]:
# Probability that a person is drunk after one breathalyzer test:
prob_drunk_givin_positive(1/1000, .08, 1)

0.012357884330202669

## Problem 2: Marginal is provided
Solving for the posterior is not too complicated when the marginal probability is provided for you. 

Suppose we have an online website where we sell a gizmo. Consider the case where a website-visitor clicks to expand the gizmo's product description. What is the probability that they will then purchase the gizmo?

Let’s assume some details:  
* 10 percent of site visitors buy the gizmo.  That's the prior: P(buy).
* 7 percent of site visitors that purchased the gizmo also clicked on the description. That's the conditional: P(click|buy).
* 5 percent of site visitors click on the product description. That's the marginal: P(click).
* What percent of site visitors will purchase the gizmo after clicking on the description? That's the posterior: P(buy|click).

Let’s plug what we know into the theorem:
* P(A|B) = P(B|A) * P(A) / P(B)   
* P(buy|click) = P(click|buy) * P(buy) / P(click)

In [0]:
# input the prior, marginal, and conditional.
prior = .10
marginal = .05
conditional = .07

In [0]:
# write the formula
def bayes(prior, marginal, conditional):
  posterior = conditional * prior / marginal
  return posterior

In [69]:
# plug it in
bayes(prior, marginal, conditional)

0.14

## Problem 3: No marginal provided!
Solving for the posterior is a little harder when the marginal is not provided; most real-world problems fall into this pattern.

Consider the case where we receive an email and the spam detector flags it (i.e., puts it in the spam folder). What is the probability it was actally spam?

Let’s assume some details:  
* 2 percent of the email we receive is spam -- that's the prior: P(Spam). 
* the spam detector is really good and when an email is spam, it flags it 99 percent of the time -- that's the conditional: P(Flagged|Spam).   
* When an email is not spam, it will flag it with a very low rate of 0.1 percent -- that's the fall-out rate: P(Flagged|not Spam).  
* What is the probability that a flagged email is actually spam? -- that's the posterior: P(Spam|Flagged) 

Let’s plug what we know into the theorem:
* P(A|B) = P(B|A) * P(A) / P(B)   
* P(Spam|Flagged) = P(Flagged|Spam) * P(Spam) / P(Flagged)

We don’t know P(B), that is P(Flagged), but we can calculate it as follows:
* P(B) = P(B|A) * P(A) + P(B|not A) * P(not A) 
* P(Flagged) = P(Flagged|Spam) * P(Spam) + P(Flagged|not Spam) * P(not Spam)

In [0]:
# input the prior, conditional, and fall-out rate.
prior = .02
conditional = .99
cond_complement = .001

In [0]:
# write the formula
def bayes_no_marginal(prior, conditional, cond_complement):
  marginal = conditional * prior + .001 * .98

  posterior = conditional * prior / marginal
  return posterior

In [75]:
# plug it in
bayes_no_marginal(prior, conditional, cond_complement)

0.9528392685274303

## Problem 4. No marginal (again)
What if only two pieces of information are available?

Let’s assume some details:  
* the condition occurs in 2% of the population -- that's the prior: P(sick). 
* when a patient is actually sick, the classifier flags them as sick 72 percent of the time -- that's the conditional: P(Flagged|Sick).   
* when the classifier says they are not sick, this is true 97 percent of the time. That's P(not Flagged | not Sick)
* What is the probability that a flagged patient is actually sick? -- that's the posterior: P(Sick|Flagged).

We don't know the marginal P(B), and we don't know the fall-out rate -- P(Flagged|not Sick) -- but we can calculate them using the formulas:

* P(B) = P(B|A) * P(A) + P(B|not A) * P(not A)
* P(B|not A) = 1 – P(not B|not A)

Which translates to: 
* P(Flagged) = P(Flagged|Sick) * P(Sick) + P(Flagged|not Sick) * P(not Sick)
* P(Flagged|not Sick) = 1 - P(not Flagged|not Sick)

In [0]:
# input the prior, conditional, and P(not B|not A).
prior = 0.02
conditional = 0.72

cond_complement = 1-0.97


In [0]:
# write the formula:
def bayes_no_marginal_no_fallout(prior, conditional, cond_complement):
  marginal = conditional * prior + cond_complement * (1-prior)

  posterior = conditional * prior / marginal
  return posterior

In [82]:
# plug it in:
bayes_no_marginal_no_fallout(prior, conditional, cond_complement)

0.32876712328767105

Sources:  
* http://learningwithdata.com/bayes-primer.html#bayes-primer  
* https://machinelearningmastery.com/intuition-for-bayes-theorem-with-worked-examples/  
* https://www.bayestheorem.net/  
* https://lucdemortier.github.io/articles/16/PerformanceMetrics
* https://towardsdatascience.com/machine-learning-an-error-by-any-other-name-a7760a702c4d
* https://ncss-wpengine.netdna-ssl.com/wp-content/themes/ncss/pdf/Procedures/NCSS/Binary_Diagnostic_Tests-Single_Sample.pdf
* https://www.dataschool.io/simple-guide-to-confusion-matrix-terminology/
* https://online.stat.psu.edu/stat507/node/71/