<a href="https://colab.research.google.com/github/nealonleo9/DS-Unit-1-Sprint-2-Statistics/blob/master/chi_test_unit_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [0]:
from scipy import stats
import pandas as pd

In [0]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-06-09 18:30:07--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.06s   

2020-06-09 18:30:07 (311 KB/s) - ‘student.zip’ saved [20478/20478]



In [0]:
!unzip student.zip

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [0]:
df = pd.read_csv('student-mat.csv', sep=';')

print(df.shape)
df.head()

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [0]:
contingency1 = pd.crosstab(df['Fedu'], df['famrel'])

contingency1

famrel  1  2   3   4   5
Fedu                    
0       0  0   1   1   0
1       1  4  15  39  23
2       3  4  23  56  29
3       1  4  15  51  29
4       3  6  14  48  25

In [0]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency1)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 6.175233131064557
p value 0.9860896514937763
degrees of freedom 16
expected frequencies table [[4.05063291e-02 9.11392405e-02 3.44303797e-01 9.87341772e-01
  5.36708861e-01]
 [1.66075949e+00 3.73670886e+00 1.41164557e+01 4.04810127e+01
  2.20050633e+01]
 [2.32911392e+00 5.24050633e+00 1.97974684e+01 5.67721519e+01
  3.08607595e+01]
 [2.02531646e+00 4.55696203e+00 1.72151899e+01 4.93670886e+01
  2.68354430e+01]
 [1.94430380e+00 4.37468354e+00 1.65265823e+01 4.73924051e+01
  2.57620253e+01]]


In [0]:
contingency = pd.crosstab(df['failures'], df['studytime'])

contingency

studytime   1    2   3   4
failures                  
0          74  158  54  26
1          16   26   7   1
2           6    7   4   0
3           9    7   0   0

In [0]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 16.21199080868576
p value 0.06258448399974005
degrees of freedom 9
expected frequencies table [[ 82.93670886 156.39493671  51.34177215  21.32658228]
 [ 13.29113924  25.06329114   8.2278481    3.41772152]
 [  4.51898734   8.52151899   2.79746835   1.16202532]
 [  4.25316456   8.02025316   2.63291139   1.09367089]]


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [0]:
import numpy as np

In [0]:
observed = pd.crosstab(df['failures'], df['studytime'])

observed

studytime   1    2   3   4
failures                  
0          74  158  54  26
1          16   26   7   1
2           6    7   4   0
3           9    7   0   0

In [0]:
observed_with_margins = pd.crosstab(df['failures'], df['studytime'], margins=True)

observed_with_margins

studytime    1    2   3   4  All
failures                        
0           74  158  54  26  312
1           16   26   7   1   50
2            6    7   4   0   17
3            9    7   0   0   16
All        105  198  65  27  395

In [0]:
observed = observed.values
observed

array([[ 74, 158,  54,  26],
       [ 16,  26,   7,   1],
       [  6,   7,   4,   0],
       [  9,   7,   0,   0]])

In [0]:
# (row_total)(column_total) / sample_size 

expected_row1_col1 = 208*66/395


expected_row1_col1


34.754430379746836

In [0]:
row_totals = df['failures'].value_counts().sort_index().values

row_totals

array([312,  50,  17,  16])

In [0]:
col_totals = df['studytime'].value_counts().sort_index().values

col_totals

array([105, 198,  65,  27])

In [0]:
sample_size = df.shape[0]

sample_size

395

In [0]:
expected = np.array([[ 0, 0,  0,  0],
       [ 0,  0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0]])

for i, col in enumerate(col_totals):
  for j, row in enumerate(row_totals): 
    expected_value = (row*col / sample_size)
    # print(expected_value, i, j)
    expected[i][j] = expected_value


expected

array([[ 82,  13,   4,   4],
       [156,  25,   8,   8],
       [ 51,   8,   2,   2],
       [ 21,   3,   1,   1]])

In [0]:
# chi 2 test static

In [0]:
((observed - expected)**2 / expected).sum().sum()

2554.0405642970136

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)