<a href="https://colab.research.google.com/github/daanishrasheed/DS-Unit-1-Sprint-2-Statistics/blob/master/DS_Unit_1_Sprint_Challenge_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science Unit 1 Sprint Challenge 2

## Exploring Data, Testing Hypotheses

In this sprint challenge you will look at a dataset of people being approved or rejected for credit.

https://archive.ics.uci.edu/ml/datasets/Credit+Approval

Data Set Information: This file concerns credit card applications. All attribute names and values have been changed to meaningless symbols to protect confidentiality of the data. This dataset is interesting because there is a good mix of attributes -- continuous, nominal with small numbers of values, and nominal with larger numbers of values. There are also a few missing values.

Attribute Information:
- A1: b, a.
- A2: continuous.
- A3: continuous.
- A4: u, y, l, t.
- A5: g, p, gg.
- A6: c, d, cc, i, j, k, m, r, q, w, x, e, aa, ff.
- A7: v, h, bb, j, n, z, dd, ff, o.
- A8: continuous.
- A9: t, f.
- A10: t, f.
- A11: continuous.
- A12: t, f.
- A13: g, p, s.
- A14: continuous.
- A15: continuous.
- A16: +,- (class attribute)

Yes, most of that doesn't mean anything. A16 is a variable that indicates whether or not a person's request for credit has been approved or denied. This is a good candidate for a y variable since we might want to use the other features to predict this one. The remaining variables have been obfuscated for privacy - a challenge you may have to deal with in your data science career.

Sprint challenges are evaluated based on satisfactory completion of each part. It is suggested you work through it in order, getting each aspect reasonably working, before trying to deeply explore, iterate, or refine any given step. Once you get to the end, if you want to go back and improve things, go for it!

## Part 1 - Load and validate the data

- Load the data as a `pandas` data frame.
- Validate that it has the appropriate number of observations (you can check the raw file, and also read the dataset description from UCI).
- UCI says there should be missing data - check, and if necessary change the data so pandas recognizes it as na
- Make sure that the loaded features are of the types described above (continuous values should be treated as float), and correct as necessary

This is review, but skills that you'll use at the start of any data exploration. Further, you may have to do some investigation to figure out which file to load from - that is part of the puzzle.

Hint: If a column has the datatype of "object" even though it's made up of float or integer values, you can coerce it to act as a numeric column by using the `pd.to_numeric()` function.

In [91]:
# TODO
import pandas as pd
col_names = ["A1", "A2", "A3",
             "A4", "A5", "A6",
             "A7", "A8", "A9",
             "A10", "A11", "A12", "A13",
             "A14", "A15", "A16"]
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data', names = col_names)
df.head(100)

A1     A2      A3 A4 A5  A6  A7  ...  A10 A11 A12  A13    A14    A15 A16
0   b  30.83   0.000  u  g   w   v  ...    t   1   f    g  00202      0   +
1   a  58.67   4.460  u  g   q   h  ...    t   6   f    g  00043    560   +
2   a  24.50   0.500  u  g   q   h  ...    f   0   f    g  00280    824   +
3   b  27.83   1.540  u  g   w   v  ...    t   5   t    g  00100      3   +
4   b  20.17   5.625  u  g   w   v  ...    f   0   f    s  00120      0   +
5   b  32.08   4.000  u  g   m   v  ...    f   0   t    g  00360      0   +
6   b  33.17   1.040  u  g   r   h  ...    f   0   t    g  00164  31285   +
7   a  22.92  11.585  u  g  cc   v  ...    f   0   f    g  00080   1349   +
8   b  54.42   0.500  y  p   k   h  ...    f   0   f    g  00180    314   +
9   b  42.50   4.915  y  p   w   v  ...    f   0   t    g  00052   1442   +
10  b  22.08   0.830  u  g   c   h  ...    f   0   t    g  00128      0   +
11  b  29.92   1.835  u  g   c   h  ...    f   0   f    g  00260    200   +
12  a  38.25   6.000  u  g   k   v  ...    f   0   t    g  00000      0   +
13  b  48.08   6.040  u  g   k   v  ...    f   0   f    g  00000   2690   +
14  a  45.83  10.500  u  g   q   v  ...    t   7   t    g  00000      0   +
15  b  36.67   4.415  y  p   k   v  ...    t  10   t    g  00320      0   +
16  b  28.25   0.875  u  g   m   v  ...    t   3   t    g  00396      0   +
17  a  23.25   5.875  u  g   q   v  ...    t  10   f    g  00120    245   +
18  b  21.83   0.250  u  g   d   h  ...    f   0   t    g  00000      0   +
19  a  19.17   8.585  u  g  cc   h  ...    t   7   f    g  00096      0   +
20  b  25.00  11.250  u  g   c   v  ...    t  17   f    g  00200   1208   +
21  b  23.25   1.000  u  g   c   v  ...    f   0   f    s  00300      0   +
22  a  47.75   8.000  u  g   c   v  ...    t   6   t    g  00000   1260   +
23  a  27.42  14.500  u  g   x   h  ...    t   1   f    g  00120     11   +
24  a  41.17   6.500  u  g   q   v  ...    t   3   t    g  00145      0   +
25  a  15.83   0.585  u  g   c   h  ...    t   2   f    g  00100      0   +
26  a  47.00  13.000  u  g   i  bb  ...    t   9   t    g  00000      0   +
27  b  56.58  18.500  u  g   d  bb  ...    t  17   t    g  00000      0   +
28  b  57.42   8.500  u  g   e   h  ...    t   3   f    g  00000      0   +
29  b  42.08   1.040  u  g   w   v  ...    t   6   t    g  00500  10000   +
.. ..    ...     ... .. ..  ..  ..  ...  ...  ..  ..  ...    ...    ...  ..
70  b  32.33   7.500  u  g   e  bb  ...    f   0   t    s  00420      0   -
71  b  34.83   4.000  u  g   d  bb  ...    f   0   t    g      ?      0   -
72  a  38.58   5.000  u  g  cc   v  ...    f   0   t    g  00980      0   -
73  b  44.25   0.500  u  g   m   v  ...    f   0   f    s  00400      0   -
74  b  44.83   7.000  y  p   c   v  ...    f   0   f    g  00160      2   -
75  b  20.67   5.290  u  g   q   v  ...    t   1   f    g  00160      0   -
76  b  34.08   6.500  u  g  aa   v  ...    f   0   t    g  00443      0   -
77  a  19.17   0.585  y  p  aa   v  ...    f   0   t    g  00160      0   -
78  b  21.67   1.165  y  p   k   v  ...    t   1   f    g  00180     20   -
79  b  21.50   9.750  u  g   c   v  ...    f   0   f    g  00140      0   -
80  b  49.58  19.000  u  g  ff  ff  ...    t   1   f    g  00094      0   -
81  a  27.67   1.500  u  g   m   v  ...    f   0   f    s  00368      0   -
82  b  39.83   0.500  u  g   m   v  ...    f   0   f    s  00288      0   -
83  a      ?   3.500  u  g   d   v  ...    f   0   t    g  00300      0   -
84  b  27.25   0.625  u  g  aa   v  ...    f   0   t    g  00200      0   -
85  b  37.17   4.000  u  g   c  bb  ...    f   0   t    s  00280      0   -
86  b      ?   0.375  u  g   d   v  ...    f   0   t    s  00928      0   -
87  b  25.67   2.210  y  p  aa   v  ...    f   0   f    g  00188      0   -
88  b  34.00   4.500  u  g  aa   v  ...    f   0   t    g  00240      0   -
89  a  49.00   1.500  u  g   j   j  ...    f   0   t    g  00100     27   -
90  b  62.50  12.750  y  p   c   h  ...    f   0   

In [92]:
df.shape

(690, 16)

In [93]:
import numpy as np
df = df.replace({'?':np.NaN, 'n':0, 'y':1})
df.head()

A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15 A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  00202    0   +
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g  00043  560   +
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  00280  824   +
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  00100    3   +
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  00120    0   +

In [94]:
df.isnull().sum()

A1     12
A2     12
A3      0
A4      6
A5      6
A6      9
A7      9
A8      0
A9      0
A10     0
A11     0
A12     0
A13     0
A14    13
A15     0
A16     0
dtype: int64

In [95]:
df.dtypes

A1      object
A2      object
A3     float64
A4      object
A5      object
A6      object
A7      object
A8     float64
A9      object
A10     object
A11      int64
A12     object
A13     object
A14     object
A15      int64
A16     object
dtype: object

In [96]:
convert_dict = {'A2': float, 
                'A11': float,
                'A14': float,
                'A15': float
               }
df = df.astype(convert_dict) 
print(df.dtypes) 

A1      object
A2     float64
A3     float64
A4      object
A5      object
A6      object
A7      object
A8     float64
A9      object
A10     object
A11    float64
A12     object
A13     object
A14    float64
A15    float64
A16     object
dtype: object


## Part 2 - Exploring data, Testing hypotheses

The only thing we really know about this data is that A16 is the class label. Besides that, we have 6 continuous (float) features and 9 categorical features.

Explore the data: you can use whatever approach (tables, utility functions, visualizations) to get an impression of the distributions and relationships of the variables. In general, your goal is to understand how the features are different when grouped by the two class labels (`+` and `-`).

For the 6 continuous features, how are they different when split between the two class labels? Choose two features to run t-tests (again split by class label) - specifically, select one feature that is *extremely* different between the classes, and another feature that is notably less different (though perhaps still "statistically significantly" different). You may have to explore more than two features to do this.

For the categorical features, explore by creating "cross tabs" (aka [contingency tables](https://en.wikipedia.org/wiki/Contingency_table)) between them and the class label, and apply the Chi-squared test to them. [pandas.crosstab](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.crosstab.html) can create contingency tables, and [scipy.stats.chi2_contingency](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2_contingency.html) can calculate the Chi-squared statistic for them.

There are 9 categorical features - as with the t-test, try to find one where the Chi-squared test returns an extreme result (rejecting the null that the data are independent), and one where it is less extreme.

**NOTE** - "less extreme" just means smaller test statistic/larger p-value. Even the least extreme differences may be strongly statistically significant.

Your *main* goal is the hypothesis tests, so don't spend too much time on the exploration/visualization piece. That is just a means to an end - use simple visualizations, such as boxplots or a scatter matrix (both built in to pandas), to get a feel for the overall distribution of the variables.

This is challenging, so manage your time and aim for a baseline of at least running two t-tests and two Chi-squared tests before polishing. And don't forget to answer the questions in part 3, even if your results in this part aren't what you want them to be.

In [0]:
from scipy import stats

plus = df[df['A16'] == "+"]
minus = df[df['A16'] == "-"]

In [98]:
a16_df = list(df.groupby("A16"))
for a in [2, 3, 8, 11, 14, 15]:
  vals = []
  for a16 in a16_df:
    vals.append(list(a16[1]["A{}".format(a)].dropna().values))
  pval = stats.ttest_ind(vals[0], vals[1], equal_var=False).pvalue
  
  print("A{}".format(a), stats.describe(vals[0]).mean, stats.describe(vals[1]).mean, pval, pval < 0.05)

A2 33.7204918032787 29.808230563002684 2.7673850124549367e-05 True
A3 5.9049511400651475 3.839947780678851 1.0158807568737146e-07 True
A8 3.427899022801302 1.2579242819843344 7.425348666782441e-16 True
A11 4.605863192182411 0.6318537859007833 4.310254123415665e-23 True
A14 164.421926910299 199.6994680851064 0.007777825082795855 True
A15 2038.85993485342 198.60574412532637 3.5433798702024966e-05 True


In [99]:
for a in [1,4,5,6,7,9,10,12,13]:
  print(pd.crosstab(df["A16"], df["A{}".format(a)], dropna=False, margins=True))
  print("")

A1     a    b  All
A16               
+     98  206  307
-    112  262  383
All  210  468  690

A4     1  l    u  All
A16                  
+     45  2  256  307
-    118  0  263  383
All  163  2  519  690

A5     g  gg    p  All
A16                   
+    256   2   45  307
-    263   0  118  383
All  519   2  163  690

A6   aa    c  cc   d   e  ff   i   j   k   m   q  r   w   x  All
A16                                                             
+    19   62  29   7  14   7  14   3  14  16  51  2  33  32  307
-    35   75  12  23  11  46  45   7  37  22  27  1  31   6  383
All  54  137  41  30  25  53  59  10  51  38  78  3  64  38  690

A7   0  bb  dd  ff    h  j  o    v  z  All
A16                                       
+    2  25   2   8   87  3  1  169  6  307
-    2  34   4  49   51  5  1  230  2  383
All  4  59   6  57  138  8  2  399  8  690

A9     f    t  All
A16               
+     23  284  307
-    306   77  383
All  329  361  690

A10    f    t  All
A16               
+

In [112]:
contingency_table1 = pd.crosstab(df["A16"], df["A1"], dropna=False, margins=True)
contingency_table2 = pd.crosstab(df["A16"], df["A4"], dropna=False, margins=True)
contingency_table3 = pd.crosstab(df["A16"], df["A5"], dropna=False, margins=True)
contingency_table4 = pd.crosstab(df["A16"], df["A6"], dropna=False, margins=True)
contingency_table5 = pd.crosstab(df["A16"], df["A7"], dropna=False, margins=True)
contingency_table6 = pd.crosstab(df["A16"], df["A9"], dropna=False, margins=True)
contingency_table7 = pd.crosstab(df["A16"], df["A10"], dropna=False, margins=True)
contingency_table8 = pd.crosstab(df["A16"], df["A12"], dropna=False, margins=True)
contingency_table9 = pd.crosstab(df["A16"], df["A13"], dropna=False, margins=True)

print(contingency_table1)
print(contingency_table2)
print(contingency_table3)
print(contingency_table4)
print(contingency_table5)
print(contingency_table6)
print(contingency_table7)
print(contingency_table8)
print(contingency_table9)


A1     a    b  All
A16               
+     98  206  307
-    112  262  383
All  210  468  690
A4     1  l    u  All
A16                  
+     45  2  256  307
-    118  0  263  383
All  163  2  519  690
A5     g  gg    p  All
A16                   
+    256   2   45  307
-    263   0  118  383
All  519   2  163  690
A6   aa    c  cc   d   e  ff   i   j   k   m   q  r   w   x  All
A16                                                             
+    19   62  29   7  14   7  14   3  14  16  51  2  33  32  307
-    35   75  12  23  11  46  45   7  37  22  27  1  31   6  383
All  54  137  41  30  25  53  59  10  51  38  78  3  64  38  690
A7   0  bb  dd  ff    h  j  o    v  z  All
A16                                       
+    2  25   2   8   87  3  1  169  6  307
-    2  34   4  49   51  5  1  230  2  383
All  4  59   6  57  138  8  2  399  8  690
A9     f    t  All
A16               
+     23  284  307
-    306   77  383
All  329  361  690
A10    f    t  All
A16               
+     9

In [0]:
observed1 = contingency_table1.values
observed2 = contingency_table2.values
observed3 = contingency_table3.values
observed4 = contingency_table4.values
observed5 = contingency_table5.values
observed6 = contingency_table6.values
observed7 = contingency_table7.values
observed8 = contingency_table8.values
observed9 = contingency_table9.values

In [121]:
chi_squared, p_value, dof, expected = stats.chi2_contingency(observed1)

print(f"Chi-Squared: {chi_squared}")
print(f"P-value: {p_value}")
print(f"Degrees of Freedom: {dof}") 
print("Expected: \n", np.array(expected))
print("")

chi_squared1, p_value1, dof1, expected1 = stats.chi2_contingency(observed2)

print(f"Chi-Squared: {chi_squared1}")
print(f"P-value: {p_value1}")
print(f"Degrees of Freedom: {dof1}") 
print("Expected: \n", np.array(expected1))
print("")

chi_squared2, p_value2, dof2, expected2 = stats.chi2_contingency(observed3)

print(f"Chi-Squared: {chi_squared2}")
print(f"P-value: {p_value2}")
print(f"Degrees of Freedom: {dof2}") 
print("Expected: \n", np.array(expected2))
print("")

chi_squared3, p_value3, dof3, expected3 = stats.chi2_contingency(observed4)

print(f"Chi-Squared: {chi_squared3}")
print(f"P-value: {p_value3}")
print(f"Degrees of Freedom: {dof3}") 
print("Expected: \n", np.array(expected3))
print("")

chi_squared4, p_value4, dof4, expected4 = stats.chi2_contingency(observed5)

print(f"Chi-Squared: {chi_squared4}")
print(f"P-value: {p_value4}")
print(f"Degrees of Freedom: {dof4}") 
print("Expected: \n", np.array(expected4))
print("")

chi_squared5, p_value5, dof5, expected5 = stats.chi2_contingency(observed6)

print(f"Chi-Squared: {chi_squared5}")
print(f"P-value: {p_value5}")
print(f"Degrees of Freedom: {dof5}") 
print("Expected: \n", np.array(expected5))
print("")

chi_squared6, p_value6, dof6, expected6 = stats.chi2_contingency(observed7)

print(f"Chi-Squared: {chi_squared6}")
print(f"P-value: {p_value6}")
print(f"Degrees of Freedom: {dof6}") 
print("Expected: \n", np.array(expected6))
print("")

chi_squared7, p_value7, dof7, expected7 = stats.chi2_contingency(observed8)

print(f"Chi-Squared: {chi_squared7}")
print(f"P-value: {p_value7}")
print(f"Degrees of Freedom: {dof7}") 
print("Expected: \n", np.array(expected7))
print("")

chi_squared8, p_value8, dof8, expected8 = stats.chi2_contingency(observed9)

print(f"Chi-Squared: {chi_squared8}")
print(f"P-value: {p_value8}")
print(f"Degrees of Freedom: {dof8}") 
print("Expected: \n", np.array(expected8))
print("")

Chi-Squared: 0.42820858770367115
P-value: 0.9801029168514122
Degrees of Freedom: 4
Expected: 
 [[ 93.79385965 209.02631579 308.17982456]
 [116.20614035 258.97368421 381.82017544]
 [210.         468.         690.        ]]

Chi-Squared: 26.22760335143097
P-value: 0.00020192080383058572
Degrees of Freedom: 6
Expected: 
 [[ 72.36535662   0.88791849 230.41484716 306.33187773]
 [ 90.63464338   1.11208151 288.58515284 383.66812227]
 [163.           2.         519.         690.        ]]

Chi-Squared: 26.227603351430975
P-value: 0.00020192080383058572
Degrees of Freedom: 6
Expected: 
 [[230.41484716   0.88791849  72.36535662 306.33187773]
 [288.58515284   1.11208151  90.63464338 383.66812227]
 [519.           2.         163.         690.        ]]

Chi-Squared: 98.32534437615317
P-value: 9.446439382040425e-10
Degrees of Freedom: 28
Expected: 
 [[ 24.02625821  60.95550693  18.24215901  13.34792123  11.12326769
   23.5813275   26.25091174   4.44930708  22.69146608  16.90736689
   34.70459519   

## Part 3 - Analysis and Interpretation

Now that you've looked at the data, answer the following questions:

- Interpret and explain the two t-tests you ran - what do they tell you about the relationships between the continuous features you selected and the class labels?
- Interpret and explain the two Chi-squared tests you ran - what do they tell you about the relationships between the categorical features you selected and the class labels?
- What was the most challenging part of this sprint challenge?

Answer with text, but feel free to intersperse example code/results or refer to it from earlier.

For all continuous variables, the p-values using Welch's t test are all less than 0.01, meaning it is highly likely that the distributions of each class is independent when looking at individual continuous variables. This shows that for all continuous variables, there is not much overlap between the distributions for the two class variables, meaning that they could be good predictors for class attribute.

For the categorical variables, the comparisons need to be done on a case by case basis. However, what the chi-squared p values show is how each category in the variable is representative of the whole distribution of the class attributes. The majority of the p-values fall under 0.01, meaning rejection of the null hypothesis that the category is representative of the categorical variable distribution.
As shown above in the printed crosstab table, the probable reason due to the higher p-values could be that there just isn't enough data for each category. However for A6(c,cc,e,m,q,w), and A7(bb,h), these categories have counts of over 20, and we can therefore determine that these values are not representative of the class attribute ratio.

The most challenging part of the sprint challenge was trying to understand more about the scipy stats chisquare function and using it properly.