<a href="https://colab.research.google.com/github/avi2nati/DS-Unit-1-Sprint-2-Statistics/blob/master/Module_2_LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [0]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-06-10 00:29:07--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip.2’

student.zip.2       100%[===================>]  20.00K  --.-KB/s    in 0.04s   

2020-06-10 00:29:07 (528 KB/s) - ‘student.zip.2’ saved [20478/20478]



In [0]:
!unzip student.zip

Archive:  student.zip
replace student-mat.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace student-por.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace student-merge.R? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace student.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [0]:
from scipy import stats
import pandas as pd
import numpy as np

In [0]:
df = pd.read_csv('student-mat.csv', sep=';')
df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [0]:
dependent1 = pd.crosstab(df['sex'], df['romantic'])
stats.chi2_contingency(dependent1)

(3.689657998622032,
 0.05475084154682915,
 1,
 array([[138.49113924,  69.50886076],
        [124.50886076,  62.49113924]]))

In [0]:
indpendent1 = pd.crosstab(df['age'], df['sex'])
stats.chi2_contingency(indpendent1)

(5.99460281380294, 0.5403796955381378, 7, array([[43.17974684, 38.82025316],
        [54.76455696, 49.23544304],
        [51.60506329, 46.39493671],
        [43.17974684, 38.82025316],
        [12.63797468, 11.36202532],
        [ 1.57974684,  1.42025316],
        [ 0.52658228,  0.47341772],
        [ 0.52658228,  0.47341772]]))

In [0]:
dependent2 = pd.crosstab(df['studytime'], df['failures'])
stats.chi2_contingency(dependent2)

(16.211990808685762,
 0.06258448399973988,
 9,
 array([[ 82.93670886,  13.29113924,   4.51898734,   4.25316456],
        [156.39493671,  25.06329114,   8.52151899,   8.02025316],
        [ 51.34177215,   8.2278481 ,   2.79746835,   2.63291139],
        [ 21.32658228,   3.41772152,   1.16202532,   1.09367089]]))

In [0]:
independent2 = pd.crosstab(df['age'], df['famsize'])
stats.chi2_contingency(independent2)

(3.3427362331429626, 0.851591182655544, 7, array([[58.33417722, 23.66582278],
        [73.98481013, 30.01518987],
        [69.7164557 , 28.2835443 ],
        [58.33417722, 23.66582278],
        [17.07341772,  6.92658228],
        [ 2.13417722,  0.86582278],
        [ 0.71139241,  0.28860759],
        [ 0.71139241,  0.28860759]]))

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [0]:
import numpy as np

In [0]:
# YOUR WORK HERE
df['famsize'].value_counts().sort_index()

GT3    281
LE3    114
Name: famsize, dtype: int64

In [0]:
df['age'].value_counts().sort_index()

15     82
16    104
17     98
18     82
19     24
20      3
21      1
22      1
Name: age, dtype: int64

In [0]:
contingency = pd.crosstab(df['famsize'], df['age'])

contingency

age      15  16  17  18  19  20  21  22
famsize                                
GT3      61  76  69  53  18   2   1   1
LE3      21  28  29  29   6   1   0   0

In [0]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

In [0]:
print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 3.342736233142963
p value 0.8515911826555439
degrees of freedom 7
expected frequencies table [[58.33417722 73.98481013 69.7164557  58.33417722 17.07341772  2.13417722
   0.71139241  0.71139241]
 [23.66582278 30.01518987 28.2835443  23.66582278  6.92658228  0.86582278
   0.28860759  0.28860759]]


In [0]:
df['famsup'].value_counts()

yes    242
no     153
Name: famsup, dtype: int64

In [0]:
df['guardian'].value_counts()

mother    273
father     90
other      32
Name: guardian, dtype: int64

In [0]:
observed = pd.crosstab(df['famsup'], df['guardian'])
observed 

guardian  father  mother  other
famsup                         
no            34     107     12
yes           56     166     20

In [0]:
observed_with_margins = pd.crosstab(df['famsup'], df['guardian'], margins=True)

observed_with_margins

guardian  father  mother  other  All
famsup                              
no            34     107     12  153
yes           56     166     20  242
All           90     273     32  395

In [0]:
observed_row1_col1 = 153*90/395
observed_row1_col1


34.860759493670884

In [0]:
row_totals = df['guardian'].value_counts().sort_index().values

row_totals

array([ 90, 273,  32])

In [0]:
col_totals = df['famsup'].value_counts().sort_index().values

col_totals

array([153, 242])

In [0]:
sample_size = df.shape[0]

sample_size

395

In [0]:
my_list = []

for i, row_total in enumerate(row_totals):
  row = []
  for j, column_total in enumerate(col_totals):
    expected_val  = ((column_total*row_total) / sample_size)
    row.append(expected_val)
  my_list.append(row)

 
my_list

[[34.860759493670884, 55.139240506329116],
 [105.74430379746835, 167.25569620253165],
 [12.39493670886076, 19.605063291139242]]

In [0]:
chi2 = ((observed - my_list)**2 / my_list).sum().sum()
chi2

0.07956846414956933

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [0]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?
is estimator is a statistic that estimates some fact about the population.

- What are hypothesis test? How are they useful?
is used to assess the plausibility of a hypothesis by using sample data. And useful for drawing conclusion based on probablity in the face of randomness.
- What is a "null hypothesis?"
is a hypothesis that says there is no statistical significance between the two variables in the hypothesis.

- What is a p-value and what does it represent?
is the probability of obtaining results as extreme as the observed results of a statistical hypothesis test, assuming that the null hypothesis is correct.

- What does it mean for something to be "statistically significant?"
A result of an experiment is said to have statistical significance, or be statistically significant.

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?
the degrees of freedom (DF) indicate the number of independent values that can vary in an analysis without breaking any constraints.

(# of columns -1)* (# of rows -1)