<a href="https://colab.research.google.com/github/StevenBryceLee/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/Copy_of_LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [21]:
# YOUR WORK HERE
#uploading data to file share
import pandas as pd
df = pd.read_csv('student-mat.csv',sep=';')
df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [22]:
df.isna().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [23]:
df.replace({'yes':1,'no':0}, inplace=True)

In [24]:
df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [10]:
# YOUR WORK HERE
from scipy import stats

In [128]:
chi2, p, dof = stats.chi2_contingency(pd.crosstab(df['Medu'],df['Fedu']))[0:3]
print('chi2: {}\np: {}\ndof: {}'.format(chi2,p,dof))

chi2: 199.97731385712396
p: 8.014562451932377e-34
dof: 16


In [131]:
chi2, p, dof = stats.chi2_contingency(pd.crosstab(df['health'],df['internet']))[0:3]
print('chi2: {}\np: {}\ndof: {}'.format(chi2,p,dof))

chi2: 5.174825445230703
p: 0.2698250561922323
dof: 4


Yes, I think this makes sense. I would expect mothers and fathers to have similar, although not completely same levels of education. I would also expect no relationship between your health and whether or not you can access the internet, since sick people have internet connections

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [44]:
df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [62]:
# YOUR WORK HERE
#Selecting the health and absences correlation
ct = pd.crosstab(df['romantic'],df['famrel'],margins = True)
ct

famrel    1   2   3    4    5  All
romantic                          
0         3  13  47  122   78  263
1         5   5  21   73   28  132
All       8  18  68  195  106  395

In [111]:
import numpy as np
#Creating a 1D array for easy elementwise comparison
observed_frequencies = ct.iloc[:-1,:-1]
observed_frequencies

famrel    1   2   3    4   5
romantic                    
0         3  13  47  122  78
1         5   5  21   73  28

In [123]:
#Need row sums and column sums
col_totals = df['romantic'].value_counts().sort_index().values
col_totals

array([263, 132])

In [122]:
row_totals = df['famrel'].value_counts().sort_index().values
row_totals

array([  8,  18,  68, 195, 106])

In [132]:
row_totals.sum()

395

In [124]:
#getting value totals
total = ct.loc['All','All']
total

395

In [125]:
#Get the expected frequencies by solving (col * row / total) for each value
expected_frequencies = np.zeros((2,5),dtype='float')
for row_position, col in enumerate(col_totals):
  for column_position, row in enumerate(row_totals):
    expected_value = row*col / sample_size
    expected_frequencies[row_position][column_position] = expected_value
expected_frequencies

array([[  5.32658228,  11.98481013,  45.27594937, 129.83544304,
         70.57721519],
       [  2.67341772,   6.01518987,  22.72405063,  65.16455696,
         35.42278481]])

In [134]:
#As list comprehension
freqs = np.zeros((2,5),dtype='float')
freqs = [[row*col / sample_size for column_position, row in enumerate(row_totals)] for row_position, col in enumerate(col_totals)]
freqs

[[5.326582278481013,
  11.984810126582278,
  45.27594936708861,
  129.83544303797467,
  70.57721518987341],
 [2.6734177215189874,
  6.015189873417722,
  22.724050632911393,
  65.16455696202532,
  35.42278481012658]]

In [126]:
chi2 = ((observed_frequencies - expected_frequencies)**2 / expected_frequencies).sum().sum()
chi2

7.24585090845923

In [127]:
stats.chi2_contingency(observed_frequencies)[0:3]

(7.24585090845923, 0.12345263307585237, 4)


## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [137]:
# YOUR WORK HERE
def elegant_readable_and_holds_reusable_code(df, col1, col2):
  '''
  This function is elegant, readable, and holds reusable code.
  It also has terrific documentation.
  Finally, it computes stats.chi2_contingency
  '''

  #Set up variables
  observed_frequencies = pd.crosstab(df[col1],df[col2]).values
  col_totals = df[col1].value_counts().sort_index().values
  row_totals = df[col2].value_counts().sort_index().values
  sample_size = col_totals.sum()

  #Fun with list comprehensions, also much faster
  expected_frequencies = [[row*col / sample_size 
                           for column_position, row in enumerate(row_totals)] 
                          for row_position, col in enumerate(col_totals)]
                          
  #Returning the chi^2 value, p-value must be calculated manually
  return ((observed_frequencies - expected_frequencies)**2 
          / expected_frequencies).sum().sum()

elegant_readable_and_holds_reusable_code(df, 'romantic', 'famrel')

7.24585090845923



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

What is a sample "estimate" in statistics?
- A sample estimate is any given statistic which is based on a sample rather than a population. For example, the sample estimate of the mean would be the mean of the sample, not the population, but should be theoretically close to the population mean if the sample is large enough

What are hypothesis test? How are they useful?
- A hypothesis test is a way to formally check whether or not a null hypothesis can be rejected with a given level of confidence. They are useful because not all relationships are so obvious that they can be seen via a graphical visualization, but they might still be useful in informing us about the data and its relationships.

What is a "null hypothesis?"
- The null hypothesis rejects association. Regardless of the test, the idea is that there is no relationship/association/effect between two variables. If we do not reject the null hypothesis, then we believe that the data does not show a relationship

What is a p-value and what does it represent?
- A p-value is given from several types of statistical tests including the t test and chi squared test. The p-value represents the probability that we see the given data if the null hypothesis is actually true

What does it mean for something to be "statistically significant?"
- Something is statistically significant if the p-value is below the prior alpha value, or level of statistical significance. In this case, we reject the null hypothesis that there is no relationship in the test.

What is a test statistic and how does it relate to a p-value?

- A test statistic represents the ratio between the distance between the observed behavior and its hypothesized value and the standard error of the data. The t-statistic, for example, is used in the t-test to determine the p-value. The relationship between the test statistic and p value is that the p-value can be found from the test statistic and degrees of freedom based on either statistical tables, or by direct integration of the probability density function

What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?
- Degrees of freedom represents the number of values in the data set calculations which can vary. This will be an integer calculated from the amount of data available for the test. For 1 and 2-sample t-tests, the degrees of freedom are the number of observations - number of columns because while you have a list of observations, any of the values can vary but the last. The last value must be fixed in order to generate the same mean from the set of data. The chi squared test gets its degrees of freedom following the same logic of the highest degree of variance and the formula (#of rows -1 ) * (# of columns - 1)


## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)