<a href="https://colab.research.google.com/github/elifulton/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/Copy_of_LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [3]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-08-11 21:24:58--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.1s    

2020-08-11 21:24:59 (154 KB/s) - ‘student.zip’ saved [20478/20478]



In [4]:
!unzip student.zip

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [5]:
df = pd.read_csv('student-mat.csv', sep=";")

In [6]:
df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [10]:
import pandas as pd
import numpy as np
from scipy import stats

In [15]:
# set up crosstab contingency

contingency_1 = pd.crosstab(df['traveltime'], df['freetime'])

contingency_1

freetime     1   2    3   4   5
traveltime                     
1           11  40  106  72  28
2            7  18   38  34  10
3            1   6    8   8   0
4            0   0    5   1   2

In [16]:
# add margins (assigned to different variable)

observed_with_margins_1 = pd.crosstab(df['traveltime'], df['freetime'], margins=True)

observed_with_margins_1

freetime     1   2    3    4   5  All
traveltime                           
1           11  40  106   72  28  257
2            7  18   38   34  10  107
3            1   6    8    8   0   23
4            0   0    5    1   2    8
All         19  64  157  115  40  395

In [17]:
# print the values out and compare

chi2, p_value, dof, expected = stats.chi2_contingency(contingency_1)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

chi2: 11.46774269441963
p value: 0.4893142424435174
dof: 12
expected_frequencies: 
 [[ 12.36202532  41.64050633 102.14936709  74.82278481  26.02531646]
 [  5.14683544  17.33670886  42.52911392  31.15189873  10.83544304]
 [  1.10632911   3.72658228   9.14177215   6.69620253   2.32911392]
 [  0.38481013   1.29620253   3.17974684   2.32911392   0.81012658]]


In [11]:
# set up second contingency, this time as failures vs studytime

contingency_2 = pd.crosstab(df['failures'], df['studytime'])

contingency_2

studytime   1    2   3   4
failures                  
0          74  158  54  26
1          16   26   7   1
2           6    7   4   0
3           9    7   0   0

In [12]:
# add margins

observed_with_margins_2 = pd.crosstab(df['failures'], df['studytime'], margins=True)

observed_with_margins_2

studytime    1    2   3   4  All
failures                        
0           74  158  54  26  312
1           16   26   7   1   50
2            6    7   4   0   17
3            9    7   0   0   16
All        105  198  65  27  395

In [14]:
# print the values out and compare

chi2, p_value, dof, expected = stats.chi2_contingency(contingency_2)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

chi2: 16.21199080868576
p value: 0.06258448399974005
dof: 9
expected_frequencies: 
 [[ 82.93670886 156.39493671  51.34177215  21.32658228]
 [ 13.29113924  25.06329114   8.2278481    3.41772152]
 [  4.51898734   8.52151899   2.79746835   1.16202532]
 [  4.25316456   8.02025316   2.63291139   1.09367089]]


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [18]:
# extract total occurrences of different values in the failures column

row_totals = df['failures'].value_counts().values

row_totals

array([312,  50,  17,  16])

In [19]:
# extract total occurrences of different values in the studytime column

column_totals = df['studytime'].value_counts().sort_index().values

column_totals

array([105, 198,  65,  27])

In [20]:
# set the size of the sample

sample_size = df.shape[0]

sample_size

395

In [21]:
# placeholder values

expected = np.array([[0.0,0.0,0.0,0.0],
                     [0.0,0.0,0.0,0.0],
                     [0.0,0.0,0.0,0.0],
                     [0.0,0.0,0.0,0.0]])

for row_index, row in enumerate(row_totals):
  for column_index, col in enumerate(column_totals):

    # calculate the expected value
    expected_value = (row*col)/sample_size
    # insert the value into the correct part of the expected numpy array
    expected[row_index][column_index] = expected_value

expected

array([[ 82.93670886, 156.39493671,  51.34177215,  21.32658228],
       [ 13.29113924,  25.06329114,   8.2278481 ,   3.41772152],
       [  4.51898734,   8.52151899,   2.79746835,   1.16202532],
       [  4.25316456,   8.02025316,   2.63291139,   1.09367089]])

In [23]:
observed = contingency_2.values

In [24]:
# we get the same chi2 value here

chi2 = ((observed - expected)**2 / expected).sum()

chi2

16.21199080868576

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)