<a href="https://colab.research.google.com/github/ilEnzio/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/ERLE_GRANGERII_LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [3]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import chisquare 

In [4]:
# YOUR WORK HERE
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-07-16 12:56:14--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.03s   

2020-07-16 12:56:15 (710 KB/s) - ‘student.zip’ saved [20478/20478]



In [5]:
!unzip student.zip

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [6]:
student_math_df = pd.read_csv("student-mat.csv", sep=";")

In [7]:
student_math_df.head(2)

school sex  age address famsize Pstatus  ...  Walc  health absences G1 G2 G3
0     GP   F   18       U     GT3       A  ...     1       3        6  5  6  6
1     GP   F   17       U     GT3       T  ...     1       3        4  5  5  6

[2 rows x 33 columns]

In [8]:
student_math_df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [9]:
student_math_df.describe(exclude="number")

school  sex address famsize  ... nursery higher internet romantic
count     395  395     395     395  ...     395    395      395      395
unique      2    2       2       2  ...       2      2        2        2
top        GP    F       U     GT3  ...     yes    yes      yes       no
freq      349  208     307     281  ...     314    375      329      263

[4 rows x 17 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [ ]:
# internet_failures_contingent = pd.crosstab(student_math_df["failures"], student_math_df["internet"])

# internet_failures_contingent


In [ ]:
# stats.chi2_contingency(internet_failures_contingent)

In [15]:
# YOUR WORK HERE
# prove two variables are likely dependent using a chi^2 test 
# step 1 create a cross tab

fail_activities_contigent = pd.crosstab(student_math_df["failures"], student_math_df["activities"])

fail_activities_contigent


activities   no  yes
failures            
0           150  162
1            24   26
2             9    8
3            11    5

In [16]:
fail_activities_contigent_mar = pd.crosstab(student_math_df["failures"], student_math_df["activities"], margins=True)
fail_activities_contigent_mar

activities   no  yes  All
failures                 
0           150  162  312
1            24   26   50
2             9    8   17
3            11    5   16
All         194  201  395

In [17]:

#H0 : The failure variable is independent of the activites variable
#Ha : The failure variable is not independent of the activities variable
#Confidence Level: 95%
stats.chi2_contingency(fail_activities_contigent)

(2.727167831192036,
 0.43563013214726376,
 3,
 array([[153.23544304, 158.76455696],
        [ 24.55696203,  25.44303797],
        [  8.34936709,   8.65063291],
        [  7.85822785,   8.14177215]]))

In [13]:
# Conclusion: Based on a ch2 statistic of 2.727 and a pvalue of .4356, I FAIL to reject 
# the null hypothesis

In [19]:
#
fail_paid_contingent = pd.crosstab(student_math_df["failures"], student_math_df["paid"])
fail_paid_contingent

paid       no  yes
failures          
0         153  159
1          37   13
2          10    7
3          14    2

In [20]:
#H0 : The failure variable is independent of the paid variable
#Ha : The failure variable is not independent of the paid variable
#Confidence Level: 95%
stats.chi2_contingency(fail_paid_contingent)

(18.537217658927684,
 0.0003407451938069661,
 3,
 array([[169.03291139, 142.96708861],
        [ 27.08860759,  22.91139241],
        [  9.21012658,   7.78987342],
        [  8.66835443,   7.33164557]]))

In [ ]:
# Conclusion: Based on a chi2 statistic of 18.53 and a pvalue of .0003, I REJECT  the 
# null hypothesis



In [21]:
dalc_paid_contingent = pd.crosstab(student_math_df["Dalc"], student_math_df["paid"])
dalc_paid_contingent

paid   no  yes
Dalc          
1     154  122
2      38   37
3      17    9
4       0    9
5       5    4

In [22]:
dalc_paid_contingent_mar = pd.crosstab(student_math_df["Dalc"], student_math_df["paid"], margins=True)
dalc_paid_contingent_mar

paid   no  yes  All
Dalc               
1     154  122  276
2      38   37   75
3      17    9   26
4       0    9    9
5       5    4    9
All   214  181  395

In [23]:
#H0 : The daily alchohol variable is independent of the paid variable
#Ha : The daily alchoho variable is NOT independent of the paid variable
#Confidence Level: 95%
stats.chi2_contingency(dalc_paid_contingent)

(12.627299951107707,
 0.01324801546828434,
 4,
 array([[149.52911392, 126.47088608],
        [ 40.63291139,  34.36708861],
        [ 14.08607595,  11.91392405],
        [  4.87594937,   4.12405063],
        [  4.87594937,   4.12405063]]))

In [24]:
test = stats.chi2_contingency(dalc_paid_contingent)


In [ ]:
# Conclusion: Based on a chi2 statistic of 12.62 and a pvalue of .013, I REJECT  the 
# null hypothesis

In [25]:
goout_romance_contingent = pd.crosstab(student_math_df["goout"], student_math_df["romantic"])
goout_romance_contingent

romantic  no  yes
goout            
1         16    7
2         67   36
3         87   43
4         60   26
5         33   20

In [27]:
#H0 : The go out variable is independent of the romantic variable
#Ha : The go out variable is not independent of the romantic variable
#Confidence Level: 95%
stats.chi2_contingency(goout_romance_contingent)

(1.043935158800679, 0.9030624031255541, 4, array([[15.31392405,  7.68607595],
        [68.57974684, 34.42025316],
        [86.55696203, 43.44303797],
        [57.26075949, 28.73924051],
        [35.28860759, 17.71139241]]))

In [ ]:
# Conclusion: Based on a chi2 statistic of 1.04 and a pvalue of .9030, I FAIL
# to reject the null hypothesis

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [28]:
# YOUR WORK HERE
# so I'll just take the last one: test whether going out and romantic relationship
# are independent variables.  Scypy concluded that they were. 

# first create a contingency aka crosstab

goout_romance_contingent = pd.crosstab(student_math_df["goout"], 
                                       student_math_df["romantic"])

In [29]:
goout_romance_contingent

romantic  no  yes
goout            
1         16    7
2         67   36
3         87   43
4         60   26
5         33   20

In [30]:
# create margin ver so we can manual see the ratios of totals
# and check to see the columns
goout_romance_contingent_m = pd.crosstab(student_math_df["goout"], 
                                       student_math_df["romantic"], margins=True)
goout_romance_contingent_m

romantic   no  yes  All
goout                  
1          16    7   23
2          67   36  103
3          87   43  130
4          60   26   86
5          33   20   53
All       263  132  395

In [31]:
# calculate some EV!!!! as an example
goout1_no_romance = 23*263/395
goout1_no_romance

15.313924050632911

In [32]:
# turn the result of the crosstab/contingency into a np array
# .values will turn any object into a np array!!!!

observed = goout_romance_contingent.values
observed

array([[16,  7],
       [67, 36],
       [87, 43],
       [60, 26],
       [33, 20]])

In [33]:
# get the row totals, value counts, sorted properly by index
#
row_totals = student_math_df["goout"].value_counts().sort_index().values
row_totals

array([ 23, 103, 130,  86,  53])

In [34]:
# the column totals (of our contingency), value counts, sorted properly by index
col_totals = student_math_df["romantic"].value_counts().sort_index().values
col_totals

array([263, 132])

In [35]:
# get the total observances, which is the same as the number
# of rows in shape
sample_size = student_math_df.shape[0]
sample_size

395

In [36]:
# create a np array of the same shape as our observance table
expected = np.array([[0.0,0.0],
                     [0.0,0.0],
                     [0.0,0.0],
                     [0.0,0.0],
                     [0.0,0.0]])

In [37]:
# with a nested for loop, populate the numpy array
for i, col in enumerate(col_totals):
  for j, row in enumerate(row_totals):
    expected_value = (row*col)/sample_size
    expected[j][i] = expected_value

expected

array([[15.31392405,  7.68607595],
       [68.57974684, 34.42025316],
       [86.55696203, 43.44303797],
       [57.26075949, 28.73924051],
       [35.28860759, 17.71139241]])

In [ ]:
# Steven's code which I don't understand...
#expected_frequencies = [[row*col / sample_size for column_position, row in enumerate(row_totals)] 
#                           for row_position, col in enumerate(col_totals)]

In [ ]:
# expected_frequencies
#soo the equation is ((obs-exp)**2/exp) sum of all those

In [43]:
ch2 = ((observed-expected)**2/expected).sum()
ch2 # this should match the scipy assert 1.04

1.043935158800679

In [ ]:
# take the chi2 and turn it into a pvalue with chi 2 applet
# https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html
# Degrees of Freedom is different with chi2
# DOF = (number of rows - 1) * (number of cols - 1)
# cat equals the number of elements in my ch2 array before the sum??
# DOF = 4
# pvalue = .90367
# Confidence Level: 95%
# Conclusion: based on a chi^2 of 1.04 and a pvalue of .9036 I FAIL to reject 
# the null hypothesis.



## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)