<a href="https://colab.research.google.com/github/AndrewArnett/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [31]:
# YOUR WORK HERE

!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-06-09 22:04:55--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip.2’

student.zip.2       100%[===================>]  20.00K  --.-KB/s    in 0.04s   

2020-06-09 22:04:55 (545 KB/s) - ‘student.zip.2’ saved [20478/20478]



In [22]:
!unzip student.zip

Archive:  student.zip
replace student-mat.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-mat.csv         
replace student-por.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-por.csv         
replace student-merge.R? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-merge.R         
replace student.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student.txt             


In [0]:
import pandas as pd
import numpy as np
from scipy.stats import chisquare
from scipy import stats

In [33]:
df = pd.read_csv('student-mat.csv', sep=';')

print(df.shape)
df.head()

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [34]:
# YOUR WORK HERE

contingency = pd.crosstab(df['Mjob'], df['failures'])

contingency

failures    0   1  2  3
Mjob                   
at_home    44   9  2  4
health     29   3  1  1
other     111  18  6  6
services   73  17  8  5
teacher    55   3  0  0

In [35]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom", dof)
print("expected frequencies table", expected)

chi2 statistic 16.845542341449672
p value 0.15550045013648148
degrees of freedom 12
expected frequencies table [[ 46.60253165   7.46835443   2.53924051   2.38987342]
 [ 26.8556962    4.30379747   1.46329114   1.37721519]
 [111.3721519   17.84810127   6.06835443   5.71139241]
 [ 81.35696203  13.03797468   4.43291139   4.1721519 ]
 [ 45.81265823   7.34177215   2.49620253   2.34936709]]


In [36]:
contingency_1 = pd.crosstab(df['famsup'], df['studytime'])

contingency_1

studytime   1    2   3   4
famsup                    
no         54   70  22   7
yes        51  128  43  20

In [37]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency_1)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom", dof)
print("expected frequencies table", expected)

chi2 statistic 10.604697392630197
p value 0.014067236846179306
degrees of freedom 3
expected frequencies table [[ 40.67088608  76.69367089  25.17721519  10.45822785]
 [ 64.32911392 121.30632911  39.82278481  16.54177215]]


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [39]:
# YOUR WORK HERE

observed = pd.crosstab(df['famsup'], df['studytime'])

observed

studytime   1    2   3   4
famsup                    
no         54   70  22   7
yes        51  128  43  20

In [40]:
observed_with_margins = pd.crosstab(df['famsup'], df['studytime'], margins=True)

observed_with_margins

studytime    1    2   3   4  All
famsup                          
no          54   70  22   7  153
yes         51  128  43  20  242
All        105  198  65  27  395

In [41]:
observed = observed.values
observed

array([[ 54,  70,  22,   7],
       [ 51, 128,  43,  20]])

In [45]:
row_totals = df['studytime'].value_counts().sort_index().values
col_totals = df['famsup'].value_counts().sort_index().values

print(row_totals)
print(col_totals)

[105 198  65  27]
[153 242]


In [46]:
sample_size = df.shape[0]

sample_size

395

In [47]:
expected = np.array([[0,0],
                     [0,0]])

for i, col in enumerate(col_totals):
  for j, row in enumerate(row_totals):
    expected_value = (row*col / sample_size)
    expected[i][j] = expected_value

expected

IndexError: ignored

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [0]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)