<a href="https://colab.research.google.com/github/HunterAshby/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [1]:
# YOUR WORK HERE
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-08-11 19:42:02--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.07s   

2020-08-11 19:42:02 (285 KB/s) - ‘student.zip’ saved [20478/20478]



In [4]:
!unzip student.zip

Archive:  student.zip
replace student-mat.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: [Errno 2] No such file or directory: 'student'
/content


In [6]:
df = pd.read_csv('student-mat.csv', sep=';')

In [8]:
df.head(10)

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10
5     GP   M   16       U     LE3       T  ...     2       5       10  15  15  15
6     GP   M   16       U     LE3       T  ...     1       3        0  12  12  11
7     GP   F   17       U     GT3       A  ...     1       1        6   6   5   6
8     GP   M   15       U     LE3       A  ...     1       1        0  16  18  19
9     GP   M   15       U     GT3       T  ...     1       5        0  14  15  15

[10 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [56]:
#runs a chi2 test on two columns and outputs the results in a readable format
def chi2_with_output(column1,column2):
  contingency = pd.crosstab(column1, column2)
  chi2, p_value, dof, expected = stats.chi2_contingency(contingency)
  if p_value < .05:
    print('The variables ' + column1.name + ' and ' + column2.name + ' are dependent')
  elif p_value > .05:
    print('The variables ' + column1.name + ' and ' + column2.name + ' are independent')
  print("chi2:", chi2)
  print("p value:", p_value)
  print("dof:", dof)
  print("expected_frequencies: \n", expected)

In [57]:
# YOUR WORK HERE
#Family Support and Study time are dependent
chi2_with_output(df['famsup'], df['studytime'])

The variables famsup and studytime are dependent
chi2: 10.604697392630197
p value: 0.014067236846179306
dof: 3
expected_frequencies: 
 [[ 40.67088608  76.69367089  25.17721519  10.45822785]
 [ 64.32911392 121.30632911  39.82278481  16.54177215]]


In [46]:
chi2_with_output(df['absences'], df['age'])

The variables absences and age are dependent
chi2: 337.9798974613335
p value: 5.494894762063509e-06
dof: 231
expected_frequencies: 
 [[2.38734177e+01 3.02784810e+01 2.85316456e+01 2.38734177e+01
  6.98734177e+00 8.73417722e-01 2.91139241e-01 2.91139241e-01]
 [6.22784810e-01 7.89873418e-01 7.44303797e-01 6.22784810e-01
  1.82278481e-01 2.27848101e-02 7.59493671e-03 7.59493671e-03]
 [1.34936709e+01 1.71139241e+01 1.61265823e+01 1.34936709e+01
  3.94936709e+00 4.93670886e-01 1.64556962e-01 1.64556962e-01]
 [1.66075949e+00 2.10632911e+00 1.98481013e+00 1.66075949e+00
  4.86075949e-01 6.07594937e-02 2.02531646e-02 2.02531646e-02]
 [1.10025316e+01 1.39544304e+01 1.31493671e+01 1.10025316e+01
  3.22025316e+00 4.02531646e-01 1.34177215e-01 1.34177215e-01]
 [1.03797468e+00 1.31645570e+00 1.24050633e+00 1.03797468e+00
  3.03797468e-01 3.79746835e-02 1.26582278e-02 1.26582278e-02]
 [6.43544304e+00 8.16202532e+00 7.69113924e+00 6.43544304e+00
  1.88354430e+00 2.35443038e-01 7.84810127e-02 7.848101

In [47]:
chi2_with_output(df['traveltime'], df['freetime'])

The variables traveltime and freetime are independent
chi2: 11.46774269441963
p value: 0.4893142424435174
dof: 12
expected_frequencies: 
 [[ 12.36202532  41.64050633 102.14936709  74.82278481  26.02531646]
 [  5.14683544  17.33670886  42.52911392  31.15189873  10.83544304]
 [  1.10632911   3.72658228   9.14177215   6.69620253   2.32911392]
 [  0.38481013   1.29620253   3.17974684   2.32911392   0.81012658]]


In [48]:
chi2_with_output(df['failures'], df['health'])

The variables failures and health are independent
chi2: 8.224511251466813
p value: 0.7673486513090713
dof: 12
expected_frequencies: 
 [[ 37.12405063  35.5443038   71.87848101  52.13164557 115.32151899]
 [  5.94936709   5.69620253  11.51898734   8.35443038  18.48101266]
 [  2.02278481   1.93670886   3.9164557    2.84050633   6.2835443 ]
 [  1.90379747   1.82278481   3.68607595   2.67341772   5.91392405]]


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [51]:
# YOUR WORK HERE
contingency_with_margins = pd.crosstab(df['famsup'], df['studytime'], margins=True)
contingency_with_margins

studytime    1    2   3   4  All
famsup                          
no          54   70  22   7  153
yes         51  128  43  20  242
All        105  198  65  27  395

In [62]:
row_total = df['famsup'].value_counts().sort_index().values
print(row_total)
column_total = df['studytime'].value_counts().sort_index().values
print(column_total)
sample = df.shape[0]
print(sample)

[153 242]
[105 198  65  27]
395


In [63]:
expected = np.array([[0.0,0.0,0.0,0.0],
                     [0.0,0.0,0.0,0.0],])
for row_index, row in enumerate(row_total):
  for column_index, col in enumerate(column_total):
    expected_value = row * col / sample
    expected[row_index][column_index] = expected_value
expected

array([[ 40.67088608,  76.69367089,  25.17721519,  10.45822785],
       [ 64.32911392, 121.30632911,  39.82278481,  16.54177215]])

In [64]:
observed = pd.crosstab(df['famsup'], df['studytime']).values
observed

array([[ 54,  70,  22,   7],
       [ 51, 128,  43,  20]])

In [68]:
chi2 = ((observed - expected)**2 / expected).sum()
chi2

10.604697392630197

In [ ]:
#DOF  = (4-1)*(2-1) == 3
#p_value = 0.1407

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE
def chi2_with_output(column1,column2):
  contingency = pd.crosstab(column1, column2)
  chi2, p_value, dof, expected = stats.chi2_contingency(contingency)
  if p_value < .05:
    print('The variables ' + column1.name + ' and ' + column2.name + ' are dependent')
  elif p_value > .05:
    print('The variables ' + column1.name + ' and ' + column2.name + ' are independent')
  print("chi2:", chi2)
  print("p value:", p_value)
  print("dof:", dof)
  print("expected_frequencies: \n", expected)



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)