## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [66]:
import pandas as pd
import numpy as np
from scipy.stats import kruskal
from scipy.stats import chisquare
from scipy.stats import normaltest
from scipy.stats import ttest_ind
from scipy import stats

In [54]:


!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip


--2020-08-12 16:09:35--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip.2’

student.zip.2       100%[===================>]  20.00K  --.-KB/s    in 0.06s   

2020-08-12 16:09:35 (320 KB/s) - ‘student.zip.2’ saved [20478/20478]



In [55]:
!unzip student.zip

Archive:  student.zip
replace student-mat.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-mat.csv         
replace student-por.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-por.csv         
replace student-merge.R? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-merge.R         
replace student.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student.txt             


In [56]:
df = pd.read_csv('student-mat.csv', sep=";")

df

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0       GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1       GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2       GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3       GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4       GP   F   16       U     GT3       T  ...     2       5        4   6  10  10
..     ...  ..  ...     ...     ...     ...  ...   ...     ...      ...  ..  ..  ..
390     MS   M   20       U     LE3       A  ...     5       4       11   9   9   9
391     MS   M   17       U     LE3       T  ...     4       2        3  14  16  16
392     MS   M   21       R     GT3       T  ...     3       3        3  10   8   7
393     MS   M   18       R     LE3       T  ...     4       5        0  11  12  10
394     MS   M   19       U     LE3       T  ...     3       5        5   8   9   9

[395 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [57]:
dep = pd.crosstab(df['romantic'], df['studytime'])
dep

studytime   1    2   3   4
romantic                  
no         79  126  36  22
yes        26   72  29   5

In [58]:
dep_margins = pd.crosstab(df['romantic'], df['studytime'], margins=True)
dep_margins


studytime    1    2   3   4  All
romantic                        
no          79  126  36  22  263
yes         26   72  29   5  132
All        105  198  65  27  395

In [59]:
chi2, p_value, dof, expected = stats.chi2_contingency(dep)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

chi2: 10.664622810031268
p value: 0.013684756707976984
dof: 3
expected_frequencies: 
 [[ 69.91139241 131.83291139  43.27848101  17.97721519]
 [ 35.08860759  66.16708861  21.72151899   9.02278481]]


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [60]:
row_totals = df['romantic'].value_counts().values

row_totals

array([263, 132])

In [61]:
column_totals = df['studytime'].value_counts().sort_index().values

column_totals

array([105, 198,  65,  27])

In [62]:
sample_size = df.shape[0]

sample_size

395

In [63]:
expected = np.array([[0.0,0.0,0.0,0.0],
                     [0.0,0.0,0.0,0.0]])

In [71]:
for row_index, row in enumerate(row_totals):
  for column_index, col in enumerate(column_totals):
    expected_value = (row*col)/sample_size
    expected[row_index][column_index] = expected_value

expected

array([[ 69.91139241, 131.83291139,  43.27848101,  17.97721519],
       [ 35.08860759,  66.16708861,  21.72151899,   9.02278481]])

In [73]:
observed = dep.values

In [75]:
chi2 = ((observed - expected)**2 / expected).sum()
chi2

10.664622810031268

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)