<a href="https://colab.research.google.com/github/bootnoodles/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [4]:
# YOUR WORK HERE
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-08-12 22:22:06--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.06s   

2020-08-12 22:22:07 (321 KB/s) - ‘student.zip’ saved [20478/20478]



In [5]:
!unzip /content/student.zip

Archive:  /content/student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [6]:
%cd content

[Errno 2] No such file or directory: 'content'
/content


In [7]:
!curl /content/student-mat.csv

curl: (3) <url> malformed


In [8]:
df = pd.read_csv('/content/student-mat.csv', sep=";")

In [9]:
df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [10]:
condition = df['sex'] == 'F'

In [11]:
femaledata = df[condition]
femaledata.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [12]:
condition2 = df['sex'] == 'M'
maledata = df[condition2]

In [13]:
maledata.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
5      GP   M   16       U     LE3       T  ...     2       5       10  15  15  15
6      GP   M   16       U     LE3       T  ...     1       3        0  12  12  11
8      GP   M   15       U     LE3       A  ...     1       1        0  16  18  19
9      GP   M   15       U     GT3       T  ...     1       5        0  14  15  15
12     GP   M   15       U     LE3       T  ...     3       5        2  14  14  14

[5 rows x 33 columns]

In [14]:
condition3 = df['Mjob'] == 'teacher'
teachparents = df[condition3]
studywparent = teachparents['studytime']
studywparent.head(15)

10    2
13    2
20    2
22    2
29    2
32    2
36    3
41    1
48    2
57    2
63    3
65    2
75    2
76    4
89    2
Name: studytime, dtype: int64

In [26]:
contingency = pd.crosstab(df['goout'], df['studytime'])
contingency

studytime   1   2   3   4
goout                    
1          10  11   1   1
2          26  46  22   9
3          29  62  29  10
4          19  55   9   3
5          21  24   4   4

#Hypothosis

##Null:
### Going out and study time are not correlated.
#Alternative:
### Going out and study time are correlated



In [27]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

chi2: 24.828734405204695
p value: 0.015655626030330563
dof: 12
expected_frequencies: 
 [[ 6.11392405 11.52911392  3.78481013  1.5721519 ]
 [27.37974684 51.63037975 16.94936709  7.04050633]
 [34.55696203 65.16455696 21.39240506  8.88607595]
 [22.86075949 43.10886076 14.15189873  5.87848101]
 [14.08860759 26.56708861  8.72151899  3.62278481]]


#This rejects our null hypothisis


In [38]:
contingency2 = pd.crosstab(df['traveltime'], df['famrel'])
contingency2

famrel      1   2   3    4   5
traveltime                    
1           5  10  44  124  74
2           2   7  20   58  20
3           0   1   4    9   9
4           1   0   0    4   3

#Hypothosis

##Null:
### Traveltime and family relationship quality are not correlated
#Alternative:
###  Traveltime and family relationship quality are correlated

In [39]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency2)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

chi2: 13.585009837400634
p value: 0.32798956620885455
dof: 12
expected_frequencies: 
 [[  5.20506329  11.71139241  44.24303797 126.87341772  68.96708861]
 [  2.16708861   4.87594937  18.42025316  52.82278481  28.71392405]
 [  0.46582278   1.04810127   3.95949367  11.35443038   6.1721519 ]
 [  0.16202532   0.36455696   1.37721519   3.94936709   2.14683544]]


#This fails to reject our null hypothisis

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [ ]:
# YOUR WORK HERE

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)