<a href="https://colab.research.google.com/github/OhOmah/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [3]:
# Using shell commands to grab the dataset 

!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-07-14 21:01:33--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.04s   

2020-07-14 21:01:34 (552 KB/s) - ‘student.zip’ saved [20478/20478]



In [4]:
# Using another shell command to unzip the file 

!unzip student.zip

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [15]:
# Now assigning the student-mat.csv to a dataset
import pandas as pd 
from scipy.stats import chisquare 
import numpy as npF
from scipy.stats import ttest_ind
from scipy import stats

df = pd.read_csv('student-mat.csv', sep=';')

df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [7]:
# Grabbing all the categorical varibles for comparison 
df.describe(exclude='number')

school  sex address famsize  ... nursery higher internet romantic
count     395  395     395     395  ...     395    395      395      395
unique      2    2       2       2  ...       2      2        2        2
top        GP    F       U     GT3  ...     yes    yes      yes       no
freq      349  208     307     281  ...     314    375      329      263

[4 rows x 17 columns]

## 1) Null Hypothesis 

The two variables are independent

## 2) Alternative Hypothesis

The two variables are dependent

## 3) Confidence Level: 95% 

In [22]:
# first off using the famsize and famsup as my first pair of dependent variables 
observed = pd.crosstab(df['famsup'], df['famsize'])

chi2, p_value, dof, expected = stats.chi2_contingency(observed)

print("Chi2 statistic:", chi2)
print("P value:", p_value)
print("Degrees of freedom:",dof)
print("Expected frequencies table: \n", expected)

Chi2 statistic: 4.535754571021557
P value: 0.03319381961068291
Degrees of freedom: 1
Expected frequencies table: 
 [[108.84303797  44.15696203]
 [172.15696203  69.84303797]]


## 4) Conclusion 

With a Chi2 Statistic of 4.53 and a P value of 0.03 it is clear to **REJECT** the Null hypothesis and accept the alternative hypothesis that the two variable are dependent of each other. 

## 1) Null Hypothesis 

The two variables are independent

## 2) Alternative Hypothesis

The two variables are dependent

## 3) Confidence Level: 95% 

In [27]:
# Doing my next pair of variables, Pstatus and famsup

observed1 = pd.crosstab(df['Pstatus'], df['famsup'])

chi2, p_value, dof, expected = stats.chi2_contingency(observed1)

print("Chi2 statistic:", chi2)
print("P value:", p_value)
print("Degrees of freedom:",dof)
print("Expected frequencies table: \n", expected)

Chi2 statistic: 0.04394008644629823
P value: 0.8339651213148701
Degrees of freedom: 1
Expected frequencies table: 
 [[ 15.88101266  25.11898734]
 [137.11898734 216.88101266]]


## 4) Conclusion

With a chi2 statistic of .04 and a P-value of 0.83 it is easy to determine that we are **NOT REJECTING** the Null Hypothesis taht the two variables are independent. 

## 1) Null Hypothesis 

The two variables are independent

## 2) Alternative Hypothesis

The two variables are dependent

## 3) Confidence Level: 95% 

In [29]:
# Now doing the school support and family support variables to see if they are dependent variables

observed2 = pd.crosstab(df['schoolsup'], df['famsup'])

chi2, p_value, dof, expected = stats.chi2_contingency(observed2)

print("Chi2 statistic:", chi2)
print("P value:", p_value)
print("Degrees of freedom:",dof)
print("Expected frequencies table: \n", expected)

Chi2 statistic: 3.711345590895456
P value: 0.05404380626633763
Degrees of freedom: 1
Expected frequencies table: 
 [[133.24556962 210.75443038]
 [ 19.75443038  31.24556962]]


## 4) Conclusion

With a Chi2 Statistic of 3.7 and a P-value of 0.5 it is determined that we have to **REJECT** the null hypothesis and accept the alternative hypothesis that the two variables are dependent. 

## 1) Null Hypothesis 

The two variables are independent

## 2) Alternative Hypothesis

The two variables are dependent

## 3) Confidence Level: 95% 

In [32]:
observed3 = pd.crosstab(df['sex'], df['Fjob'])

chi2, p_value, dof, expected = stats.chi2_contingency(observed3)

print("Chi2 statistic:", chi2)
print("P value:", p_value)
print("Degrees of freedom:",dof)
print("Expected frequencies table: \n", expected)

Chi2 statistic: 4.747741078161316
P value: 0.31417349121841276
Degrees of freedom: 4
Expected frequencies table: 
 [[ 10.53164557   9.47848101 114.26835443  58.45063291  15.27088608]
 [  9.46835443   8.52151899 102.73164557  52.54936709  13.72911392]]


## 4) Conclusion

With a chi2 statistic of 4.74 and a P value of 0.31 it is easy to **NOT REJECT** the null hypothesis that the two variables are independent of each other. 

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [39]:
# I'm going to work with the pstatus and famsup chi2 test. 
# looking at the crosstab with margins to get the totals
observed1_margin = pd.crosstab(df['Pstatus'], df['famsup'], margins=True)
observed1_margin

famsup    no  yes  All
Pstatus               
A         17   24   41
T        136  218  354
All      153  242  395

In [41]:
# Getting the row totals

row_totals = df['Pstatus'].value_counts().sort_index().values

row_totals

array([ 41, 354])

In [42]:
# Now getting the column totals 

col_totals = df['famsup'].value_counts().sort_index().values

col_totals

array([153, 242])

In [43]:
sample_size = df.shape[0]

sample_size

395

In [47]:
# Now writing a for loop that's going to automaticlly go through the dataset and apply the formula to find the expected values

expected = np.array([[0.0,0.0],
                     [0.0,0.0]])

for row_position, col in enumerate(col_totals):
  for column_position, row in enumerate(row_totals):
    expected_value = (row*col) / sample_size
    expected[row_position][column_position] = expected_value
  

expected

array([[ 15.88101266, 137.11898734],
       [ 25.11898734, 216.88101266]])

## 1) Null Hypothesis 

The two variables are independent

## 2) Alternative Hypothesis

The two variables are dependent

## 3) Confidence Level: 95% 

In [55]:
# now time to find the chi2 stat

chi2 = ((observed1 - expected)** 2 / expected).sum().sum()

chi2

582.8587400690714

## 4) Conclusion: 

I ended up with a value that does not match the value I got when I used scipy, I'm going to have to look at it again and see where I went wrong. 

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)