<a href="https://colab.research.google.com/github/rdukewiesenb/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [1]:
# Import
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt


from scipy.stats import normaltest
from scipy.stats import kruskal

In [2]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-08-12 15:21:49--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.1s    

2020-08-12 15:21:49 (146 KB/s) - ‘student.zip’ saved [20478/20478]



In [3]:
!unzip student.zip

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [4]:
df = pd.read_csv('student-mat.csv', sep=";")
df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [5]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


##############################################################

#### **Two pairs of variables that are dependent (are associated with one another)**

##### Null: Age of student and number of absences are dependent variables.
##### Alternative: Age of student and number of absences are independent variables.
##### Confidence Level: 95%

##### Conclusion: Because of a chi2 of 337.98, a p-value of 0.000005, and a dof of 231, I must reject the null hypothesis that age of student and number of absences are dependent variables.

In [6]:
#####Contingency#####

In [7]:
# start with a contingency 
contingency1 = pd.crosstab(df['age'], df['absences'])
print(contingency1.shape)
contingency1.head()

(8, 34)


absences  0   1   2   3   4   5   6   7   ...  26  28  30  38  40  54  56  75
age                                       ...                                
15        28   0  22   0   9   0  10   0  ...   1   0   0   0   0   0   0   0
16        30   0  20   0  14   1  11   1  ...   0   0   0   0   0   1   0   0
17        24   1  15   4  18   0   7   2  ...   0   1   1   0   0   0   1   0
18        26   2   7   2   8   3   3   4  ...   0   0   0   0   0   0   0   1
19         6   0   1   1   3   1   0   0  ...   0   0   0   1   1   0   0   0

[5 rows x 34 columns]

In [8]:
# then use the stats.chi2_contingency() function

chi2, p_value, dof, expected = stats.chi2_contingency(contingency1)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

chi2: 337.9798974613335
p value: 5.494894762063509e-06
dof: 231
expected_frequencies: 
 [[2.38734177e+01 6.22784810e-01 1.34936709e+01 1.66075949e+00
  1.10025316e+01 1.03797468e+00 6.43544304e+00 1.45316456e+00
  4.56708861e+00 6.22784810e-01 3.52911392e+00 6.22784810e-01
  2.49113924e+00 6.22784810e-01 2.49113924e+00 6.22784810e-01
  1.45316456e+00 2.07594937e-01 1.03797468e+00 2.07594937e-01
  8.30379747e-01 2.07594937e-01 6.22784810e-01 2.07594937e-01
  2.07594937e-01 2.07594937e-01 2.07594937e-01 2.07594937e-01
  2.07594937e-01 2.07594937e-01 2.07594937e-01 2.07594937e-01
  2.07594937e-01 2.07594937e-01]
 [3.02784810e+01 7.89873418e-01 1.71139241e+01 2.10632911e+00
  1.39544304e+01 1.31645570e+00 8.16202532e+00 1.84303797e+00
  5.79240506e+00 7.89873418e-01 4.47594937e+00 7.89873418e-01
  3.15949367e+00 7.89873418e-01 3.15949367e+00 7.89873418e-01
  1.84303797e+00 2.63291139e-01 1.31645570e+00 2.63291139e-01
  1.05316456e+00 2.63291139e-01 7.89873418e-01 2.63291139e-01
  2.6329113

In [9]:
#####Chi^2 test#####

In [10]:
# define the expected values
# row = age
# column = absences

row_totals = df['age'].value_counts().sort_index().values
row_totals

array([ 82, 104,  98,  82,  24,   3,   1,   1])

In [11]:
col_totals = df['absences'].value_counts().sort_index().values
col_totals

array([115,   3,  65,   8,  53,   5,  31,   7,  22,   3,  17,   3,  12,
         3,  12,   3,   7,   1,   5,   1,   4,   1,   3,   1,   1,   1,
         1,   1,   1,   1,   1,   1,   1,   1])

In [12]:
w_margins = pd.crosstab(df['age'], df['absences'], margins=True)
w_margins

absences    0  1   2  3   4  5   6  7   8  ...  26  28  30  38  40  54  56  75  All
age                                        ...                                     
15         28  0  22  0   9  0  10  0   7  ...   1   0   0   0   0   0   0   0   82
16         30  0  20  0  14  1  11  1   5  ...   0   0   0   0   0   1   0   0  104
17         24  1  15  4  18  0   7  2   3  ...   0   1   1   0   0   0   1   0   98
18         26  2   7  2   8  3   3  4   6  ...   0   0   0   0   0   0   0   1   82
19          6  0   1  1   3  1   0  0   1  ...   0   0   0   1   1   0   0   0   24
20          1  0   0  0   1  0   0  0   0  ...   0   0   0   0   0   0   0   0    3
21          0  0   0  1   0  0   0  0   0  ...   0   0   0   0   0   0   0   0    1
22          0  0   0  0   0  0   0  0   0  ...   0   0   0   0   0   0   0   0    1
All       115  3  65  8  53  5  31  7  22  ...   1   1   1   1   1   1   1   1  395

[9 rows x 35 columns]

In [13]:
# now define sample size

sample_size = df.shape[0]
sample_size

395

In [14]:
# and create the placeholder values for expected frequencies
expected = np.array([[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]])

In [15]:
expected

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [16]:
for row in row_totals:
  for col in col_totals:
    exp_value = row*col/sample_size


In [17]:
# and create the placeholder values for expected frequencies
expected = np.array([[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
                    [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]])
                    


for row_index, row in enumerate(row_totals):
  for col_index, col in enumerate(col_totals):
    exp_value = (row*col)/sample_size
    expected[row_index][col_index] = exp_value


expected

array([[2.38734177e+01, 6.22784810e-01, 1.34936709e+01, 1.66075949e+00,
        1.10025316e+01, 1.03797468e+00, 6.43544304e+00, 1.45316456e+00,
        4.56708861e+00, 6.22784810e-01, 3.52911392e+00, 6.22784810e-01,
        2.49113924e+00, 6.22784810e-01, 2.49113924e+00, 6.22784810e-01,
        1.45316456e+00, 2.07594937e-01, 1.03797468e+00, 2.07594937e-01,
        8.30379747e-01, 2.07594937e-01, 6.22784810e-01, 2.07594937e-01,
        2.07594937e-01, 2.07594937e-01, 2.07594937e-01, 2.07594937e-01,
        2.07594937e-01, 2.07594937e-01, 2.07594937e-01, 2.07594937e-01,
        2.07594937e-01, 2.07594937e-01],
       [3.02784810e+01, 7.89873418e-01, 1.71139241e+01, 2.10632911e+00,
        1.39544304e+01, 1.31645570e+00, 8.16202532e+00, 1.84303797e+00,
        5.79240506e+00, 7.89873418e-01, 4.47594937e+00, 7.89873418e-01,
        3.15949367e+00, 7.89873418e-01, 3.15949367e+00, 7.89873418e-01,
        1.84303797e+00, 2.63291139e-01, 1.31645570e+00, 2.63291139e-01,
        1.05316456e+00,

In [18]:
observed = contingency1.values
observed.shape

(8, 34)

In [19]:
# now, for the final part: chi2 test!

chi2 = ((observed - expected)**2 / expected).sum()
chi2

337.9798974613335

##############################################################

#### **Two pairs of variables that are independent (have no significant relationship)**

##### Null: Sex of student and amount of freetime (hours) are dependent variables.
##### Alternative: Sex of student and amount of freetime (hours) are independent variables.
##### Confidence Level: 95%

##### Conclusion: Because of a chi2 of 27.76, a p-value of 0.0000013, and a dof of 4, I must reject the null hypothes that age of student and number of absences are dependent variables.

In [20]:
#####Contingency#####

In [21]:
# convert variables in 'sex' from strings to ints --> rename to M=0, F=1
df = df.replace({"M" : 0, "F" : 1})
df.head()



school  sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP    1   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP    1   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP    1   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP    1   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP    1   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [76]:
contingency2 = pd.crosstab(df['sex'], df['freetime'])
print(contingency2.shape)
contingency2.head()

(2, 5)


freetime   1   2   3   4   5
sex                         
0          4  26  64  61  32
1         15  38  93  54   8

In [88]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency2)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

chi2: 27.76321210039277
p value: 1.3929800482563467e-05
dof: 4
expected_frequencies: 
 [[ 8.99493671 30.29873418 74.32658228 54.44303797 18.93670886]
 [10.00506329 33.70126582 82.67341772 60.55696203 21.06329114]]


In [24]:
#####Chi^2 test#####

In [78]:
# define the expected values
# row = sex
# column = freetime

row_totals2 = df['sex'].value_counts().sort_index().values
row_totals2

array([187, 208])

In [93]:
col_totals2 = df['freetime'].value_counts().sort_index().values
col_totals2

array([ 19,  64, 157, 115,  40])

In [80]:
w_margins2 = pd.crosstab(df['sex'], df['freetime'], margins=True)
w_margins2

freetime   1   2    3    4   5  All
sex                                
0          4  26   64   61  32  187
1         15  38   93   54   8  208
All       19  64  157  115  40  395

In [81]:
sample_size2 = df.shape[0]
sample_size2

395

In [82]:
expected2 = np.array([[0,0,0,0,0],
                     [0,0,0,0,0]])
                   

expected2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [83]:
for row in row_totals2:
  for col in col_totals2:
    exp_value = row*col/sample_size2


In [95]:

for row_index, row in enumerate(row_totals2):
  for col_index, col in enumerate(col_totals2):
    exp_value = (row*col)/sample_size2
    expected2[row_index][col_index] = exp_value


expected2

array([[ 8, 30, 74, 54, 18],
       [10, 33, 82, 60, 21]])

In [96]:
observed2 = contingency2.values
observed2.shape

(2, 5)

In [97]:
chi2 = ((observed2 - expected2)**2 / expected2).sum()
chi2

29.061785542273352

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [102]:
# age and absences
# chi2 result from 

# chi2 result from NumPy: 23.87
w_margins = pd.crosstab(df['age'], df['absences'], margins=True)
w_margins


absences    0  1   2  3   4  5   6  7   8  ...  26  28  30  38  40  54  56  75  All
age                                        ...                                     
15         28  0  22  0   9  0  10  0   7  ...   1   0   0   0   0   0   0   0   82
16         30  0  20  0  14  1  11  1   5  ...   0   0   0   0   0   1   0   0  104
17         24  1  15  4  18  0   7  2   3  ...   0   1   1   0   0   0   1   0   98
18         26  2   7  2   8  3   3  4   6  ...   0   0   0   0   0   0   0   1   82
19          6  0   1  1   3  1   0  0   1  ...   0   0   0   1   1   0   0   0   24
20          1  0   0  0   1  0   0  0   0  ...   0   0   0   0   0   0   0   0    3
21          0  0   0  1   0  0   0  0   0  ...   0   0   0   0   0   0   0   0    1
22          0  0   0  0   0  0   0  0   0  ...   0   0   0   0   0   0   0   0    1
All       115  3  65  8  53  5  31  7  22  ...   1   1   1   1   1   1   1   1  395

[9 rows x 35 columns]

In [104]:
# write out the equation -- (row_total*col_total) / total_observations
(115*82)/395

23.873417721518987

In [98]:
# sex and freetime
w_margins2 = pd.crosstab(df['sex'], df['freetime'], margins=True)
w_margins2

freetime   1   2    3    4   5  All
sex                                
0          4  26   64   61  32  187
1         15  38   93   54   8  208
All       19  64  157  115  40  395

In [106]:
(187*19)/395

8.99493670886076

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [30]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)