<a href="https://colab.research.google.com/github/James-Hagerman/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/Mod_2_Assign_2_LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [33]:
import pandas as pd 
import numpy as np 
from scipy import stats

In [1]:
# YOUR WORK HERE
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-08-11 20:46:41--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.1s    

2020-08-11 20:46:42 (154 KB/s) - ‘student.zip’ saved [20478/20478]



In [2]:
!unzip student.zip

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [3]:
%cd student

[Errno 2] No such file or directory: 'student'
/content


In [4]:
!curl student-mat.csv

curl: (6) Could not resolve host: student-mat.csv


In [16]:
df = pd.read_csv('student-mat.csv', sep = ';')

print(df.shape)
df.head()

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [14]:
# YOUR WORK HERE

contingency = pd.crosstab(df['sex'],df['age'])

contingency

age  15  16  17  18  19  20  21  22
sex                                
F    38  54  58  43  14   1   0   0
M    44  50  40  39  10   2   1   1

In [15]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

# due to a chi2 of 5.9 and a p-value of .54, we fail to reject the 
# null hypothesis that these variables are independent

chi2: 5.99460281380294
p value: 0.5403796955381378
dof: 7
expected_frequencies: 
 [[43.17974684 54.76455696 51.60506329 43.17974684 12.63797468  1.57974684
   0.52658228  0.52658228]
 [38.82025316 49.23544304 46.39493671 38.82025316 11.36202532  1.42025316
   0.47341772  0.47341772]]


In [53]:
contingency2 = pd.crosstab(df['freetime'],df['failures'], margins = False)

contingency2

failures    0   1  2  3
freetime               
1          13   5  1  0
2          52   7  4  1
3         134  11  6  6
4          86  20  5  4
5          27   7  1  5

In [54]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency2)

print("chi2:", chi2)
print("p value:", p_value)
print("dof:", dof)
print("expected_frequencies: \n", expected)

# Due to a chi2 of 21.63 and a p-value of .042, we reject the null hypothesis,
# And instead suggest that the two variables are dependent. 

chi2: 21.63057016713022
p value: 0.041874946639631754
dof: 12
expected_frequencies: 
 [[ 15.00759494   2.40506329   0.81772152   0.76962025]
 [ 50.55189873   8.10126582   2.75443038   2.59240506]
 [124.01012658  19.87341772   6.75696203   6.35949367]
 [ 90.83544304  14.55696203   4.94936709   4.65822785]
 [ 31.59493671   5.06329114   1.72151899   1.62025316]]


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [55]:
# YOUR WORK HERE

contingency2

failures    0   1  2  3
freetime               
1          13   5  1  0
2          52   7  4  1
3         134  11  6  6
4          86  20  5  4
5          27   7  1  5

In [56]:
row_totals = df['freetime'].value_counts().values

row_totals

array([157, 115,  64,  40,  19])

In [49]:
column_totals = df['failures'].value_counts().values

col_totals

array([312,  50,  17,  16])

In [50]:
sample_size = df.shape[0]

sample_size

395

In [58]:
expected = np.array([[0.0,0.0,0.0,0.0],
                     [0.0,0.0,0.0,0.0],
                     [0.0,0.0,0.0,0.0],
                     [0.0,0.0,0.0,0.0],
                     [0.0,0.0,0.0,0.0]])

for row_index, row in enumerate(row_totals):
  for column_index, col in enumerate(column_totals):
    expected_value = (row*col)/sample_size
    expected[row_index][column_index] = expected_value

expected

array([[124.01012658,  19.87341772,   6.75696203,   6.35949367],
       [ 90.83544304,  14.55696203,   4.94936709,   4.65822785],
       [ 50.55189873,   8.10126582,   2.75443038,   2.59240506],
       [ 31.59493671,   5.06329114,   1.72151899,   1.62025316],
       [ 15.00759494,   2.40506329,   0.81772152,   0.76962025]])

In [63]:
observed = contingency2.values

observed

array([[ 13,   5,   1,   0],
       [ 52,   7,   4,   1],
       [134,  11,   6,   6],
       [ 86,  20,   5,   4],
       [ 27,   7,   1,   5]])

In [65]:
chi2 = ((observed - expected)**2 / expected).sum()

chi2

481.5829424716437

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)